### ISSUE TITLE
BETAFPVF435 target

### ISSUE THREAD

**Issue by NobodyExceptHim** [betaflight/config#360]
### Is your feature request related to a problem? Please describe

There is a betafpvf435 target inside firmware flasher according to betaflight 4.5 but there are no builds to select from.

### Describe the solution you'd like

Know if its a config issue or if there is no plan to add support to this board

### Describe alternatives you've considered

ATbetaflight but it is too old

**Comment by haslinghuis** [comment]
Get configurator from https://github.com/betaflight/betaflight-configurator/releases

![image](https://github.com/betaflight/config/assets/8344830/bb7718c4-5cc3-4dc6-be45-0ed29659fd42)

**Comment by NobodyExceptHim** [comment]
<img width="690" alt="Screenshot 2024-03-22 at 16 48 04" src="https://github.com/betaflight/config/assets/70288263/7d16b848-1c73-49ee-b865-54de388ff4be">
I have the newest version as you can see in the top left corner :(

**Comment by NobodyExceptHim** [comment]
I'm terribly sorry. Release candidates ;)... Thank you!

**Comment by NobodyExceptHim** [comment]
@haslinghuis Could I also ask you (cause i truly don't know how to check it) if this version allows built in elrs v3 with this target?

**Comment by haslinghuis** [comment]
If you mean ERLS SPI - the firmware supports V3.

You can ask question on Betaflight [Discord Server](https://discord.com/invite/gV4XSq3fus)
