### ISSUE TITLE
Barometer not working for BF4.5.0-RC3 on SKYSTARSH7HD target

### ISSUE THREAD

**Issue by mmes** [betaflight/config#371]
Baro (BMP280) does not work for the SKYSTARSH7HD target. I don't 100% follow [the git history](https://github.com/betaflight/config/commits/master/configs/SKYSTARSH7HD/config.h), but the current SPI->I2C change does not seem to work and `BARO_SPI_BMP280` define crashes the BF4.5 build. Please fix this config.

**Comment by haslinghuis** [comment]
@mmes should be fixed in https://github.com/betaflight/config/pull/386
