### ISSUE TITLE
`DRONIUSF7` - missing gyros (and other components)

### ISSUE THREAD

**Issue by nerdCopter** [betaflight/config#411]
https://github.com/betaflight/config/blob/2ceeadcfc74da037569ae408bd5b6be5de7d3bc6/configs/DRONIUSF7/config.h#L26

Target seemingly created by @cvetaevvitaliy 2020.  suspect mpu6000.

gyro orientation?

**Comment by cvetaevvitaliy** [comment]
Please add to config '#define GYRO_1_ALIGN CW0_DEG_FLIP' for gyro orientation

**Comment by nerdCopter** [comment]
because this is a config.h (not a unified-target), it need gyro model, flash-chip model, max7456, baro, etc defined as well. thank you.

**Comment by cvetaevvitaliy** [comment]
> because this is a config.h (not a unified-target), it need gyro model, flash-chip model, max7456, baro, etc defined as well. thank you.

Hi @nerdCopter fixed
Thanks
