### ISSUE TITLE
no gyro available in my configuration tab

### ISSUE THREAD

**Issue by jihad231** [betaflight/config#561]
i got a new esc and i just flash then  i got these problem it was work fine before the flash

the submit support data     36cab847-2eca-43f6-8661-d9235b80905b

**Comment by nerdCopter** [comment]
duplicate: https://github.com/betaflight/config/issues/552

if it is a clone of `OMNIBUSF4SD`, then you will need to add custom define for your gyro, flash, etc as the `OMNIBUSF4SD` will not be modified for clone hardware.
https://hackmd.io/@nerdCopter/ByheaoLQh

please use Discord for support: https://discord.betaflight.com/
