### ISSUE TITLE
New ID for FLYTEX LTD

### ISSUE THREAD

**Issue by MatviiG** [betaflight/config#606]
Hi,

could you please add an ID for FLYTEX LTD
website: https://www.flytex.pro/
Targets: FLYTEX405 ; FLYTEX722

BR,
Matvii

**Comment by haslinghuis** [comment]
@sugaarK

**Comment by MatviiG** [comment]
> Checkout https://betaflight.com/docs/development/manufacturer/requirements-for-submission-of-targets
> 
> @sugaarK

Hi @haslinghuis sorry for bothering you. I checked documentation You pointed - it says I need ID which I'm asking here, Information about company already provided, targets will be provided just after ID obtained. Or we should provide hardware design for review first?

**Comment by nerdCopter** [comment]
you simply need to choose a 4-cahracter ID and pull-request to https://github.com/betaflight/config/blob/master/Manufacturers.md in the same format.

maybe `FLYT`, maybe `FTEX`

example (in the proper sort order):
```
|FLYT|FLYTEX LTD|https://www.flytex.pro/|
```
Note, there is a UK company named FLYTEX LTD (oil company)

**Comment by cvetaevvitaliy** [comment]
@MatviiG You make clones on StingBee electronics

**Comment by cvetaevvitaliy** [comment]
@sugaarK Please pay attention.

**Comment by MatviiG** [comment]
> @MatviiG You make clones on StingBee electronics
In case we make clones - why we need our own id for configuration?

**Comment by cvetaevvitaliy** [comment]
> > @MatviiG You make clones on StingBee electronics
> > @cvetaevvitaliy In case we make clones - why we need our own id for configuration?

hm, Say hello to Andrew
Stealing electronics drawings from a factory and appropriating them for yourself is not very nice.

**Comment by sugaarK** [comment]
this isn't going any where until the issue of cloning is addressed

**Comment by MatviiG** [comment]
@cvetaevvitaliy  So. as You talked yesterday with us about FC we are going to produce - are there still objections from your side about it? Is it still is blocked?

**Comment by cvetaevvitaliy** [comment]
> @cvetaevvitaliy  So. as You talked yesterday with us about FC we are going to produce - are there still objections from your side about it? Is it still is blocked?

No, we thought about the option of cooperation, nothing more. 
Need time for final.
