### ISSUE TITLE
cloud build error - impossible to update FC target HGLRCF722AIOV2 for betaflight 4.5.x 

### ISSUE THREAD

**Issue by sghizz** [betaflight/config#611]
### Describe the bug

Hi, i have a hglrc specter AIO 25A. The target is HGLRCF722AIOV2. It comes with BF 4.4.x. 
It is impossible to update to 4.5 or 4.5.1. Cloud build failed. I have betaflight configurator 10.10 on windows. if i cloud build a 4.4.x version it works. if i select any other target it works with 4.5.x... Can you verify where is the problem? 

### To Reproduce

//

### Expected behavior

//

### Support ID

```txt
//
```

### Flight controller

hglrc specter aio 25A

**Comment by haslinghuis** [comment]
Other possibility it is a new board and there is simply no configuration available yet.

**Comment by sghizz** [comment]
Oh yes, but who cooks the firmware for this boards? I would send him a
request…

Il giorno lun 18 nov 2024 alle 22:40 Mark Haslinghuis <
***@***.***> ha scritto:

**Comment by haslinghuis** [comment]
Resolved in #633
